version: '3.8'

services:
  app:
    image: python:3.11-slim
    container_name: my_python_app
    volumes:
      - ./:/app
    working_dir: /app
    command: python -m http.server 8000
    ports:
      - "8000:8000"